In [1]:
import pandas as pd

In [2]:
# Path to the 'Player Names Master.xlsx' file and import as df.
player_names_master_path = "/Users/nacho/Desktop/FCMidtjylland/Data/RawData/Player Names Master.xlsx"
player_names_master = pd.read_excel(player_names_master_path)

In [3]:
# Dictionary creation for mapping full names to their player names
name_mapping = player_names_master.groupby('full_name')['player_name'].apply(list).to_dict()

# Creation of a list to store the rows of the new DataFrame
new_rows = []

# Fill the new_rows list with the transformed data
for full_name, player_names in name_mapping.items():
# It is assumed that there are two ways to call each player. Cases with a single name are still handled.
    new_row = {
        'First Name': player_names[0],
        'First Name Initial': player_names[1] if len(player_names) > 1 else None,  # To handle cases with a single name
        'Full Name': full_name
    }
    new_rows.append(new_row)

# Create the new DataFrame with the new rows
player_names_master = pd.DataFrame(new_rows)

In [4]:
player_names_master = player_names_master.sort_values(by='Full Name')
player_names_master

   First Name First Name Initial          Full Name
0       Aiden           Aiden S.        Aiden Scott
1   Alexander       Alexander W.    Alexander White
2    Benjamin        Benjamin M.  Benjamin Martinez
3      Carter          Carter M.      Carter Murphy
4      Daniel          Daniel H.        Daniel Hill
5       David           David P.       David Parker
6      Elijah          Elijah A.    Elijah Anderson
7       Ethan           Ethan H.       Ethan Harris
8       Henry           Henry A.        Henry Allen
9        Jack            Jack B.        Jack Bailey
10    Jackson         Jackson Y.      Jackson Young
11      Jacob           Jacob N.       Jacob Nelson
12      James           James D.        James Davis
13       John            John R.    John Richardson
14     Joseph          Joseph E.       Joseph Evans
15       Liam            Liam J.       Liam Johnson
16      Logan           Logan J.      Logan Jackson
17      Lucas           Lucas T.       Lucas Taylor
18       Luke            Luke R.          Luke Reed
19      Mason           Mason T.       Mason Thomas
20    Matthew         Matthew G.      Matthew Green
21    Michael         Michael C.     Michael Carter
22       Noah            Noah S.         Noah Smith
23     Oliver          Oliver W.      Oliver Wilson
24       Owen            Owen R.        Owen Rivera
25     Samuel          Samuel A.       Samuel Adams
26  Sebastian       Sebastian W.   Sebastian Wright
27    William         William B.      William Brown
28      Wyatt           Wyatt C.       Wyatt Cooper

In [5]:
# Path to the output directory and export of the data frame
output_path = "/Users/nacho/Desktop/FCMidtjylland/Data/ProcessedData/Player Names Master.xlsx"
player_names_master.to_excel(output_path, index=False)

print(f"File successfully exported in --> {output_path}")

File successfully exported in --> /Users/nacho/Desktop/FCMidtjylland/Data/ProcessedData/Player Names Master.xlsx